version: "3.8"
services:
  server:
    build: .
    container_name: rajarani-server
    ports:
      - "80:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - MONGO_URI=mongodb://host.docker.internal:27017/rajarani
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
volumes:
  mongo_data:
