# version: "3.8"
# services:
#   server:
#     image: raja-rani:latest
#     container_name: rajarani-server
#     ports:
#       - "80:5001"
#     environment:
#       - NODE_ENV=production
#       - PORT=5001
#       - MONGO_URI=mongodb://host.docker.internal:27017/rajarani
#     extra_hosts:
#       - "host.docker.internal:host-gateway"
#     restart: always
# volumes:
#   mongo_data:

version: "3.9"
services:
  client:
    image: raja-rani-ui:latest
    ports:
      - "80:80"
    depends_on:
      - server
  server:
    image: raja-rani-server:latest
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://host.docker.internal:27017/rajarani
    ports:
      - "5001:5001"
